#+title: La communicabilité des codes sources

Toute entité chargée d'une mission de service public doit publier tout
document produit ou reçu dans le cadre de cette mission, quelle qu'en
soit la date, le lieu de conservation et le support.  Les codes
sources, en tant que documents administratifs, relèvent de cette
obligation (voir l'avis CADA du 8 janvier 2015 n°[[http://cada.data.gouv.fr/20144578/][20144578]]).

Les codes sources concernés sont, au même titre que n'importe quelle
autre donnée administrative publiable en open data, celles « dont la
publication présente un intérêt économique, social, sanitaire ou
environnemental. »

Voir les articles [[https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=BCCCCF5B5E15C3F6CABA0952E9B5A818.tplgfr21s_3?idArticle=LEGIARTI000033219073&cidTexte=LEGITEXT000031366350&dateTexte=20190307][L323-2]] et [[https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=6A856B120BAA63F8153E8D6C8CDF40D4.tplgfr21s_3?idArticle=LEGIARTI000034504991&cidTexte=LEGITEXT000031366350&dateTexte=20190307][D323-2-1]] (pour les licences) du Code des
relations entre le public et les administrations, ainsi que l'article
46, II, 4 de la [[https://www.legifrance.gouv.fr/affichLoiPubliee.do?idDocument=JORFDOLE000031589829&type=general&legislature=14][loi pour une République numérique]].

* Pour qu'un code source soit communicable

- Il doit être achevé : dès lors qu'une version du code est utilisée
  en production, cette version est considérée comme achevée.
- Sa communication ne doit pas porter atteinte :
  - au secret commercial et industriel ;
  - à la sûreté de l'État, à la sécurité publique, à la sécurité des
    personnes ou à la sûreté des systèmes d'information des
    administrations ;
  - à la recherche et à la prévention, par les services compétents,
    d'infractions de toute nature.
- L'obligation de communicabilité porte sur les collectivités de plus
  de 3500 habitants et les organismes publics de plus de 50 agents.

En dehors de ces limites, toute personne ou toute administration peut
demander la communication d'un code source.

* Licences applicables à la publication d'un code source

La liste des licences sous lesquelles un code source peut être placé
au moment de sa diffusion est [[https://www.data.gouv.fr/fr/licences][accessible ici]].
