#+title: Open data logiciels : les niveaux d'ouverture

Ce document sert de guide pour l'ouverture des logiciels libres des
organismes publics, dans le cadre de la mise en oeuvre de la loi pour
une République numérique du 7 octobre 2016.

Nous commençons par délimiter la finalité de ce guide puis rappelons
le contexte juridique pour l'ouverture des codes sources de
l'administration avant de décrire les niveaux d'ouverture.

Pour toute question relative à l'ouverture des codes sources dans
votre administration, n'hésitez pas à écrire à =opensource@data.gouv.fr=

* Finalité de ce document

Ce document porte seulement sur la question de l'ouverture des codes
sources.

Il ne détaille pas les *bonnes pratiques* d'un projet libre, que ce soit
sur le plan des pratiques techniques ou de la communication au sein et
autour des projets.  Des éléments de ces bonnes pratiques peuvent être
trouvés dans la [[https://www.numerique.gouv.fr/publications/politique-logiciel-libre/][Politique de contribution de l'État aux logiciels
libres]].

Il ne porte pas sur la question de la *transparence algorithmique* : la
possibilité pour un citoyen de demander des comptes sur les décisions
individuelles le concernant et mobilisant un traitement algorithmique
ne préjuge pas de l'existence de ce traitement sous forme de logiciel
ni de la communicabilité du logiciel, si celui-ci existe.

Ce n'est pas un guide pour la gouvernance des logiciels libres : ce
sujet est un sujet à part entière.  Nous distinguons la maintenance /a
minima/ (niveau B 📗) et la recherche active de contributeurs (niveau A
📘) mais ces aspects ne couvrent qu'une petite partie de la question
de la gouvernance.

*Sa finalité* est d'aider les organismes publics à prioriser les codes
sources pouvant être communiqués afin de construire une stratégie
proactive d'ouverture logicielle.

* La communicabilité des codes sources

Toute entité chargée d'une mission de service public doit publier tout
document produit ou reçu dans le cadre de cette mission, quelle qu'en
soit la date, le lieu de conservation et le support.  Les codes
sources, en tant que documents administratifs, relèvent de cette
obligation (voir l'avis CADA du 8 janvier 2015 n°[[http://cada.data.gouv.fr/20144578/][20144578]]).

Pour qu'un code source soit communicable :

- il doit être achevé : dès lors qu'une version du code est utilisée
  en production, cette version est considérée comme achevée.
- sa communication ne doit pas porter atteinte :
  - au secret commercial et industriel ;
  - à la sûreté de l'État, à la sécurité publique, à la sécurité des
    personnes ou à la sûreté des systèmes d'information des
    administrations ;
  - à la recherche et à la prévention, par les services compétents,
    d'infractions de toute nature.
- l'obligation de communicabilité porte sur les collectivités de plus
  de 3500 habitants et les organismes publics de plus de 50 agents.

En dehors de ces limites, toute personne ou toute administration peut
demander la communication d'un code source.

La liste des licences sous lesquelles un code source peut être placé
au moment de sa diffusion est [[https://www.data.gouv.fr/fr/licences][accessible ici]].

* Les niveaux d'ouverture

- 📘 Niveau A - *contributif* :: Le code source est publié, les
     contributions extérieures sont activement recherchées et
     traitées.

- 📗 Niveau B - *ouvert* :: Le code source est publié, les contributions
     extérieures sont traitées mais non activement recherchées.

- 📙 Niveau C - *publié* :: Le code source est publié mais les
     contributions extérieures ne sont pas traitées.

- 📕 Niveau D - *fermé* :: Le code source n'est pas publié.

* Maintenance et contributions

Ce document est maintenu par Bastien Guerry à Etalab.

Vous pouvez contribuer en proposant une /pull request/ ou en [[https://github.com/etalab/opendata-logiciels/issues/new][ouvrant une
issue]].

Pour toute question relative à l'ouverture des codes sources dans
votre administration, n'hésitez pas à écrire à =opensource@data.gouv.fr=

* Licence

© 2018 Direction interministérielle du numérique et du système
d'information et de communication de l'État

© 2018 Les contributeurs accessibles via l'historique du dépôt.

Les contenus accessibles dans ce dépôt sont placés sous Licence
Ouverte 2.0 -- voir le fichier =LO.md= dans ce répertoire.  Vous êtes
libre de réutiliser les contenus de ce dépôt sous les conditions
précisées dans cette licence.
