#+title: Open data logiciels : guide sur l'ouverture

* À qui s'adresse ce guide ?

Ce guide s'adresse aux organismes publics, et plus particulièrement
aux personnes chargés de l'ouverture des codes sources logiciels dans
ces organismes.

* À quoi sert-il ?

Ce guide sert à aider les organismes publics à définir une politique
d'ouverture des logiciels libres qu'ils produisent, dans le cadre de
la mise en oeuvre de la loi pour une République numérique du 7
octobre 2016.

Il vient en complément de la Politique de contribution aux logiciels
libres de l’État, [[https://www.numerique.gouv.fr/publications/politique-logiciel-libre/][publiée]] en mai 2018, laquelle est doublement
limitée: (1) elle ne s'adresse pas aux collectivités territoriales ;
(2) elle acte le principe selon lequel les agents publics peuvent
publier du code source et contribuer à des logiciels libres, mais elle
n'aide pas les organismes publics à répondre à la question « Quels
logiciels ouvrir en priorité ? »

*Ce guide a pour vocation de répondre à la question : « Quels logiciels ouvrir en priorité ? »*

* Prérequis et compléments

Ce guide suppose que vous avez bien compris ce que [[file:hors-scope.org][ce document n'est
pas]], que vous avez pris connaissance de la [[https://www.numerique.gouv.fr/publications/politique-logiciel-libre/][politique de contribution
aux logiciels libres de l’État]] et du [[cadre-juridique.org][cadre juridique]] dans lequel
s'applique la communicabilité des codes sources logiciels produits par
des organismes publics.

* Quels degrés d'ouverture pour les codes sources ?

Nous proposons de distinguer les quatre degrés d'ouverture suivants :

- 📘 Niveau A - *contributif* :: Le code source est publié, les
  contributions extérieures sont activement recherchées et traitées.

- 📗 Niveau B - *ouvert* :: Le code source est publié, les contributions
  extérieures sont traitées mais non activement recherchées.

- 📙 Niveau C - *publié* :: Le code source est publié mais les
  contributions extérieures ne sont pas traitées.

- 📕 Niveau D - *fermé* :: Le code source n'est pas publié.

* Quels logiciels ouvrir à quel degré ?

Tous les logiciels développés par un organisme public n'ont pas
vocation à être ouvert au même degré.

Nous proposons deux critères :

1. Le logiciel est-il *un module utile à d'autres logiciels libres* (ou
   un logiciel « monolithique » sans utilité pour d'autres logiciels
   libres) ?

2. Le logiciel répond-il a un *besoin générique* (ou à un besoin
   spécifique à l'organisme qui le produit) ?

Le niveau A est recommandé pour les logiciels répondant à ces deux
critères ; le niveau B est recommandé pour ceux répondant seulement au
critère de généricité ; le niveau C pour ceux ne répondant qu'au
critère de modularité.

Pour les logiciels ne répondant à aucun des deux critères, le niveau D
est admissible, tant qu'aucun citoyen n'exige la communication du code
source en question, selon le cadre juridique définit dans la loi pour
République numérique.

Bien sûr, ces critères sont /grossiers/ et /relatifs/  : la modularité et
la généricité ne s'évaluent pas dans l'absolu.  Mais ces deux notions
aident à *prioriser les ouvertures logicielles*.  Le but est de savoir
où mettre de l'énergie pour augmenter les contributions reçues et
données.

* Exemples de mise en oeuvre

- Une collectivité territoriale développe un outil de correction
  grammaticale pour LibreOffice.  Ce logiciel est un module d'un
  logiciel libre existant et il répond à un besoin générique : il est
  pertinent d'en faire un *logiciel libre « contributif »* (niveau A).

- Une administration développe un outil pour organiser la collecte de
  données sur le web (/scraping/).  C'est un outil web « monolithique_»
  mais qui répond à un besoin rencontré hors de l'administration : il
  peut être publié comme *logiciel libre « ouvert »* (niveau B).

- Une administration centrale développe un thème pour les sites
  qu'elle publie à l'aide de Jekyll.  Ce thème est un module d'un
  logiciel libre existant mais il répond à un besoin spécifique de
  l'organisme public : son code source peut être publié, mais sans
  recherche active de contributeurs ni maintenance particulière à
  l'égard des contributions extérieures (niveau C).

Chaque organisme peut tenter de prioriser les logiciels à ouvrir
en fonction de ces critères.

* Maintenance de ce document et contributions

Ce document est maintenu par Bastien Guerry à Etalab.

Pour toute question, vous pouvez écrire à =opensource@data.gouv.fr=.

Vous pouvez aussi contribuer avec des suggestions en [[https://github.com/etalab/opendata-logiciels/issues/new][ouvrant une issue]]
ou en proposant une /pull request/.

* Licence

2018-2019 Direction interministérielle du numérique et du système
d'information et de communication de l'État.

2018-2019 Les contributeurs accessibles via l'historique du dépôt.

Les contenus accessibles dans ce dépôt sont placés sous [[file:LO.md][Licence
Ouverte 2.0]].  Vous êtes libre de réutiliser les contenus de ce dépôt
sous les conditions précisées dans cette licence.
